version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  petclinic:
    image: petclinic-functional:0.2.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_HOST=mysql
      - SPRING_APPLICATION_JSON={"logging.level.org.springframework.boot":"TRACE"}
    ports:
      - "8080:8080"
    depends_on:
      - mysql