version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - ./src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  petclinic:
    image: petclinic-functional:0.2.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - MYSQL_HOST=mysql
    ports:
      - "8080:8080"
    depends_on:
      - mysql